
project_id = "mqbtzqgvbhooyzkwfhzy"

[api.endpoint]
local = ""
production = ""

[[functions]]
name = "box-auth"
verify_jwt = true

[[functions]]
name = "dropbox-auth"
verify_jwt = true

[[functions]]
name = "google-drive-auth"
verify_jwt = true

[[functions]]
name = "list-files"
verify_jwt = true

[[functions]]
name = "list-provider-files"
verify_jwt = true

[[functions]]
name = "onedrive-auth"
verify_jwt = true

[[functions]]
name = "api-key-management"
verify_jwt = true

[[functions]]
name = "mega-auth"
verify_jwt = true

[[functions]]
name = "amazon-s3-auth"
verify_jwt = true

[[functions]]
name = "storage-api"
verify_jwt = true

[[functions]]
name = "pcloud-auth"
verify_jwt = true

[[functions]]
name = "yandex-disk-auth"
verify_jwt = true

[[functions]]
name = "icedrive-auth"
verify_jwt = true

[[functions]]
name = "backblaze-auth"
verify_jwt = true

[[functions]]
name = "sync-auth"
verify_jwt = true
