/// <reference types="@cloudflare/workers-types" />

interface Env { DB: D1Database; FILES: R2Bucket; ALLOWED_ORIGINS: string; SESSION_TTL_DAYS?: string; RESEND_API_KEY?:string; FROM_EMAIL?:string; APP_URL?:string; ADMIN_EMAIL?:string }
type User = { id:string; email:string; display_name:string; avatar_url:string|null; role:'user'|'admin'; settings:string };
type Ctx = { env:Env; request:Request; url:URL; requestId:string; user?:User; apiPermissions?:string[]; params:Record<string,string> };
const enc = new TextEncoder();
const json = (body:unknown, status=200, headers:HeadersInit={}) => new Response(JSON.stringify(body), {status, headers:{'content-type':'application/json; charset=utf-8',...headers}});
const error = (message:string, status=400, requestId?:string) => json({error:{message,requestId}}, status);
const id = () => crypto.randomUUID();
const now = () => new Date().toISOString();
const b64 = (bytes:Uint8Array) => btoa(String.fromCharCode(...bytes)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');
const randomToken = () => b64(crypto.getRandomValues(new Uint8Array(32)));
const hash = async (value:string) => [...new Uint8Array(await crypto.subtle.digest('SHA-256',enc.encode(value)))].map(x=>x.toString(16).padStart(2,'0')).join('');
async function passwordHash(password:string,salt:string){ const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']); return b64(new Uint8Array(await crypto.subtle.deriveBits({name:'PBKDF2',salt:enc.encode(salt),iterations:210000,hash:'SHA-256'},key,256))); }
const safeUser = (u:User) => ({id:u.id,email:u.email,display_name:u.display_name,avatar_url:u.avatar_url,role:u.role,settings:parse(u.settings,{})});
function parse<T>(v:string|null|undefined, fallback:T):T { try{return v?JSON.parse(v):fallback}catch{return fallback} }
async function body<T>(r:Request):Promise<T>{ if(!(r.headers.get('content-type')||'').includes('application/json')) throw new HttpError(415,'Expected application/json.'); try{return await r.json<T>()}catch{throw new HttpError(400,'Invalid JSON body.')} }
class HttpError extends Error { constructor(public status:number,message:string){super(message)} }
function cors(req:Request,env:Env){ const origin=req.headers.get('origin'); const allowed=(env.ALLOWED_ORIGINS||'').split(',').map(x=>x.trim()); const h=new Headers({'vary':'Origin','access-control-allow-headers':'Authorization, Content-Type, X-API-Key','access-control-allow-methods':'GET,POST,PATCH,DELETE,OPTIONS'}); if(origin && allowed.includes(origin))h.set('access-control-allow-origin',origin); return h; }
async function session(ctx:Ctx, required=true){ const bearer=ctx.request.headers.get('authorization')?.match(/^Bearer\s+(.+)$/i)?.[1],apiKey=ctx.request.headers.get('x-api-key'); const credential=bearer||apiKey;if(!credential){if(required)throw new HttpError(401,'Authentication required.');return} const tokenHash=await hash(credential); const u=bearer?await ctx.env.DB.prepare(`SELECT u.id,u.email,u.display_name,u.avatar_url,u.role,u.settings FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>datetime('now')`).bind(tokenHash).first<User>():await ctx.env.DB.prepare(`SELECT u.id,u.email,u.display_name,u.avatar_url,u.role,u.settings FROM api_keys k JOIN users u ON u.id=k.user_id WHERE k.key_hash=?`).bind(tokenHash).first<User>(); if(!u){if(required)throw new HttpError(401,'Session or API key is invalid.');return}if(apiKey){const key=await ctx.env.DB.prepare('SELECT permissions FROM api_keys WHERE key_hash=?').bind(tokenHash).first<{permissions:string}>();ctx.apiPermissions=parse(key?.permissions,[]);await ctx.env.DB.prepare('UPDATE api_keys SET last_used_at=? WHERE key_hash=?').bind(now(),tokenHash).run()}ctx.user=u; }
async function audit(ctx:Ctx,action:string,type?:string,resource?:string,details:unknown={}){ await ctx.env.DB.prepare('INSERT INTO audit_logs(id,user_id,action,resource_type,resource_id,details,request_id) VALUES(?,?,?,?,?,?,?)').bind(id(),ctx.user?.id||null,action,type||null,resource||null,JSON.stringify(details),ctx.requestId).run(); }
function validatePassword(v:unknown){if(typeof v!=='string'||v.length<10||v.length>128)throw new HttpError(400,'Password must be 10–128 characters.');return v}
function validateName(v:unknown,label='Name'){if(typeof v!=='string'||!v.trim()||v.trim().length>255||/[\\/]/.test(v))throw new HttpError(400,`${label} is invalid.`);return v.trim()}
async function createSession(ctx:Ctx,user:User){const token=randomToken(), days=Math.min(Number(ctx.env.SESSION_TTL_DAYS||30),90); const expires=new Date(Date.now()+days*864e5).toISOString(); await ctx.env.DB.prepare('INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES(?,?,?,?)').bind(id(),user.id,await hash(token),expires).run(); return {token,expires_at:expires,user:safeUser(user)}}

type Handler=(c:Ctx)=>Promise<Response>;
const routes:{method:string;pattern:URLPattern;auth?:boolean;admin?:boolean;handler:Handler}[]=[];
const route=(method:string,path:string,handler:Handler,opts:{auth?:boolean;admin?:boolean}={})=>routes.push({method,pattern:new URLPattern({pathname:path}),handler,...opts});
route('GET','/api/health',async c=>json({status:'ok',service:'cloudgather-api',time:now()}));
route('POST','/api/auth/register',async c=>{const x=await body<{email:string,password:string,displayName?:string}>(c.request);const email=String(x.email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new HttpError(400,'Enter a valid email.');const password=validatePassword(x.password),salt=randomToken(),uid=id();try{await c.env.DB.prepare('INSERT INTO users(id,email,password_hash,password_salt,display_name,role) VALUES(?,?,?,?,?,?)').bind(uid,email,await passwordHash(password,salt),salt,(x.displayName||email.split('@')[0]).trim().slice(0,100),email===c.env.ADMIN_EMAIL?.toLowerCase()?'admin':'user').run()}catch{throw new HttpError(409,'An account with this email already exists.')}const u=await c.env.DB.prepare('SELECT id,email,display_name,avatar_url,role,settings FROM users WHERE id=?').bind(uid).first<User>();c.user=u!;await audit(c,'user.registered','user',uid);return json(await createSession(c,u!),201)});
route('POST','/api/auth/login',async c=>{const x=await body<{email:string,password:string}>(c.request);const u=await c.env.DB.prepare('SELECT * FROM users WHERE email=? COLLATE NOCASE').bind(String(x.email||'').trim()).first<User&{password_hash:string,password_salt:string}>();if(!u||await passwordHash(String(x.password||''),u.password_salt)!==u.password_hash)throw new HttpError(401,'Email or password is incorrect.');c.user=u;await audit(c,'user.login');return json(await createSession(c,u))});
route('GET','/api/auth/me',async c=>json({user:safeUser(c.user!)}),{auth:true});
route('POST','/api/auth/logout',async c=>{const t=c.request.headers.get('authorization')!.replace(/^Bearer\s+/i,'');await c.env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await hash(t)).run();return new Response(null,{status:204})},{auth:true});
route('PATCH','/api/profile',async c=>{const x=await body<{display_name?:string;avatar_url?:string|null;settings?:unknown}>(c.request);const name=x.display_name===undefined?c.user!.display_name:validateName(x.display_name,'Display name');await c.env.DB.prepare('UPDATE users SET display_name=?,avatar_url=?,settings=?,updated_at=? WHERE id=?').bind(name,x.avatar_url===undefined?c.user!.avatar_url:x.avatar_url,x.settings===undefined?c.user!.settings:JSON.stringify(x.settings),now(),c.user!.id).run();const u=await c.env.DB.prepare('SELECT id,email,display_name,avatar_url,role,settings FROM users WHERE id=?').bind(c.user!.id).first<User>();return json({user:safeUser(u!)})},{auth:true});
route('DELETE','/api/account',async c=>{const objects=await c.env.FILES.list({prefix:`${c.user!.id}/`});await Promise.all(objects.objects.map(o=>c.env.FILES.delete(o.key)));await c.env.DB.prepare('DELETE FROM users WHERE id=?').bind(c.user!.id).run();return new Response(null,{status:204})},{auth:true});
route('GET','/api/files',async c=>{const parent=c.url.searchParams.get('parent');const search=c.url.searchParams.get('search');let sql='SELECT * FROM files WHERE user_id=?',args:unknown[]=[c.user!.id];if(search){sql+=' AND filename LIKE ? ESCAPE \'\\\'';args.push(`%${search.replace(/[\\%_]/g,'\\$&')}%`)}else if(parent){sql+=' AND parent_folder_id=?';args.push(parent)}else if(c.url.searchParams.get('all')!=='1')sql+=' AND parent_folder_id IS NULL';const rows=await c.env.DB.prepare(sql+' ORDER BY is_folder DESC, filename COLLATE NOCASE LIMIT 500').bind(...args).all();return json({files:rows.results})},{auth:true});
route('POST','/api/folders',async c=>{const x=await body<{name:string;parent_folder_id?:string|null}>(c.request),name=validateName(x.name,'Folder name');let path=`/${name}`;if(x.parent_folder_id){const p=await c.env.DB.prepare('SELECT path FROM files WHERE id=? AND user_id=? AND is_folder=1').bind(x.parent_folder_id,c.user!.id).first<{path:string}>();if(!p)throw new HttpError(404,'Parent folder not found.');path=`${p.path}/${name}`}const fid=id();try{await c.env.DB.prepare('INSERT INTO files(id,user_id,filename,path,is_folder,parent_folder_id) VALUES(?,?,?,?,1,?)').bind(fid,c.user!.id,name,path,x.parent_folder_id||null).run()}catch{throw new HttpError(409,'An item with this name already exists here.')}await audit(c,'folder.created','file',fid);return json({file:await c.env.DB.prepare('SELECT * FROM files WHERE id=?').bind(fid).first()},201)},{auth:true});
route('POST','/api/files/upload',async c=>{const form=await c.request.formData(),file=form.get('file'),parent=String(form.get('parent_folder_id')||'')||null;if(!(file instanceof File)||!file.size)throw new HttpError(400,'Choose a non-empty file.');if(file.size>100*1024*1024)throw new HttpError(413,'File exceeds the 100 MB limit.');let base='';if(parent){const p=await c.env.DB.prepare('SELECT path FROM files WHERE id=? AND user_id=? AND is_folder=1').bind(parent,c.user!.id).first<{path:string}>();if(!p)throw new HttpError(404,'Parent folder not found.');base=p.path}const fid=id(),key=`${c.user!.id}/${fid}/${file.name}`;try{await c.env.FILES.put(key,file.stream(),{httpMetadata:{contentType:file.type||'application/octet-stream'}});await c.env.DB.prepare('INSERT INTO files(id,user_id,filename,path,size,mime_type,parent_folder_id,provider_file_id) VALUES(?,?,?,?,?,?,?,?)').bind(fid,c.user!.id,file.name,`${base}/${file.name}`,file.size,file.type||null,parent,key).run()}catch(e){await c.env.FILES.delete(key);throw e}await audit(c,'file.uploaded','file',fid,{size:file.size});return json({file:await c.env.DB.prepare('SELECT * FROM files WHERE id=?').bind(fid).first()},201)},{auth:true});
route('PATCH','/api/files/:id',async c=>{const x=await body<{filename?:string;is_starred?:boolean}>(c.request),f=await c.env.DB.prepare('SELECT * FROM files WHERE id=? AND user_id=?').bind(c.params.id,c.user!.id).first<Record<string,unknown>>();if(!f)throw new HttpError(404,'File not found.');const filename=x.filename===undefined?f.filename:validateName(x.filename),oldPath=String(f.path),newPath=x.filename===undefined?oldPath:oldPath.slice(0,oldPath.length-String(f.filename).length)+filename;try{await c.env.DB.batch([c.env.DB.prepare('UPDATE files SET filename=?,path=?,is_starred=?,updated_at=? WHERE id=? AND user_id=?').bind(filename,newPath,x.is_starred===undefined?f.is_starred:Number(x.is_starred),now(),c.params.id,c.user!.id),...(Number(f.is_folder)?[c.env.DB.prepare('UPDATE files SET path=?||substr(path,?) WHERE user_id=? AND path LIKE ?').bind(newPath,oldPath.length+1,c.user!.id,`${oldPath}/%`)]:[])])}catch{throw new HttpError(409,'An item with this name already exists here.')}return json({file:await c.env.DB.prepare('SELECT * FROM files WHERE id=?').bind(c.params.id).first()})},{auth:true});
route('DELETE','/api/files/:id',async c=>{const f=await c.env.DB.prepare('SELECT * FROM files WHERE id=? AND user_id=?').bind(c.params.id,c.user!.id).first<{path:string;provider_file_id:string|null;is_folder:number}>();if(!f)throw new HttpError(404,'File not found.');const rows=f.is_folder?await c.env.DB.prepare('SELECT provider_file_id FROM files WHERE user_id=? AND path LIKE ?').bind(c.user!.id,`${f.path}/%`).all<{provider_file_id:string}>():{results:[]};await Promise.all([...rows.results.map(x=>x.provider_file_id),f.provider_file_id].filter(Boolean).map(k=>c.env.FILES.delete(k!)));await c.env.DB.prepare('DELETE FROM files WHERE id=? AND user_id=?').bind(c.params.id,c.user!.id).run();return new Response(null,{status:204})},{auth:true});
route('GET','/api/files/:id/download',async c=>{const f=await c.env.DB.prepare('SELECT filename,mime_type,provider_file_id FROM files WHERE id=? AND user_id=? AND is_folder=0').bind(c.params.id,c.user!.id).first<{filename:string;mime_type:string;provider_file_id:string}>();if(!f)throw new HttpError(404,'File not found.');const o=await c.env.FILES.get(f.provider_file_id);if(!o)throw new HttpError(404,'Stored object not found.');return new Response(o.body,{headers:{'content-type':f.mime_type||'application/octet-stream','content-disposition':`attachment; filename*=UTF-8''${encodeURIComponent(f.filename)}`,'etag':o.httpEtag}})},{auth:true});
route('GET','/api/providers',async c=>json({providers:(await c.env.DB.prepare('SELECT id,provider_name,provider_user_email,status,total_space,used_space,priority,created_at FROM storage_providers WHERE user_id=? ORDER BY priority').bind(c.user!.id).all()).results}),{auth:true});
route('DELETE','/api/providers/:id',async c=>{await c.env.DB.prepare('DELETE FROM storage_providers WHERE id=? AND user_id=?').bind(c.params.id,c.user!.id).run();return new Response(null,{status:204})},{auth:true});
route('GET','/api/api-keys',async c=>json({keys:(await c.env.DB.prepare('SELECT id,name,key_prefix,permissions,last_used_at,created_at FROM api_keys WHERE user_id=? ORDER BY created_at DESC').bind(c.user!.id).all()).results}),{auth:true});
route('POST','/api/api-keys',async c=>{const x=await body<{name:string;permissions?:string[]}>(c.request),token=`cg_${randomToken()}`,kid=id();await c.env.DB.prepare('INSERT INTO api_keys(id,user_id,name,key_hash,key_prefix,permissions) VALUES(?,?,?,?,?,?)').bind(kid,c.user!.id,validateName(x.name),await hash(token),token.slice(0,10),JSON.stringify(x.permissions||['read'])).run();return json({key:{id:kid,name:x.name,key_prefix:token.slice(0,10),permissions:x.permissions||['read'],key:token}},201)},{auth:true});
route('DELETE','/api/api-keys/:id',async c=>{await c.env.DB.prepare('DELETE FROM api_keys WHERE id=? AND user_id=?').bind(c.params.id,c.user!.id).run();return new Response(null,{status:204})},{auth:true});
route('GET','/api/blog',async c=>json({posts:(await c.env.DB.prepare('SELECT slug,title,excerpt,published_at FROM blog_posts WHERE published=1 ORDER BY published_at DESC').all()).results}));
route('GET','/api/admin/stats',async c=>{const [users,files,providers,posts,activity]=await c.env.DB.batch([...['users','files','storage_providers','blog_posts'].map(t=>c.env.DB.prepare(`SELECT count(*) count FROM ${t}`)),c.env.DB.prepare('SELECT id,action,resource_type,created_at FROM audit_logs ORDER BY created_at DESC LIMIT 10')]);return json({userCount:(users.results[0] as any).count,fileCount:(files.results[0] as any).count,providerCount:(providers.results[0] as any).count,blogCount:(posts.results[0] as any).count,recentActivities:activity.results,degraded:false})},{auth:true,admin:true});
route('GET','/api/admin/settings',async c=>{const rows=await c.env.DB.prepare('SELECT key,value FROM system_settings ORDER BY key').all();return json({settings:rows.results.map((r:any)=>({id:r.key,setting_key:r.key,setting_value:parse(r.value,null),description:null}))})},{auth:true,admin:true});
route('PATCH','/api/admin/settings',async c=>{const x=await body<{changes:{key:string;value:unknown}[]}>(c.request);if(!Array.isArray(x.changes)||x.changes.length>100)throw new HttpError(400,'Invalid settings payload.');await c.env.DB.batch(x.changes.map(v=>c.env.DB.prepare('INSERT INTO system_settings(key,value,updated_at) VALUES(?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').bind(v.key,JSON.stringify(v.value),now())));return json({ok:true})},{auth:true,admin:true});
route('GET','/api/admin/users',async c=>{const search=(c.url.searchParams.get('search')||'').slice(0,100);const users=await c.env.DB.prepare('SELECT id,email,display_name,role,created_at FROM users WHERE display_name LIKE ? OR email LIKE ? ORDER BY created_at DESC LIMIT 200').bind(`%${search}%`,`%${search}%`).all();const admins=await c.env.DB.prepare("SELECT id,email,created_at FROM users WHERE role='admin' ORDER BY created_at").all();return json({users:users.results,admins:admins.results})},{auth:true,admin:true});
route('POST','/api/admin/users/role',async c=>{const x=await body<{email:string;role:string}>(c.request),email=String(x.email||'').toLowerCase();if(x.role!=='admin'&&x.role!=='user')throw new HttpError(400,'Invalid role.');if(email===c.user!.email&&x.role!=='admin')throw new HttpError(409,"You cannot remove your own admin access.");const result=await c.env.DB.prepare('UPDATE users SET role=?,updated_at=? WHERE email=?').bind(x.role,now(),email).run();if(!result.meta.changes)throw new HttpError(404,'User not found.');return json({ok:true})},{auth:true,admin:true});
route('GET','/api/export',async c=>{const [files,providers,shares]=await c.env.DB.batch([c.env.DB.prepare('SELECT * FROM files WHERE user_id=?').bind(c.user!.id),c.env.DB.prepare('SELECT id,provider_name,provider_user_email,status,total_space,used_space,created_at FROM storage_providers WHERE user_id=?').bind(c.user!.id),c.env.DB.prepare('SELECT * FROM file_shares WHERE owner_id=?').bind(c.user!.id)]);return json({exported_at:now(),profile:safeUser(c.user!),files:files.results,providers:providers.results,shares:shares.results})},{auth:true});
route('PATCH','/api/auth/password',async c=>{const x=await body<{password:string}>(c.request),password=validatePassword(x.password),salt=randomToken();await c.env.DB.batch([c.env.DB.prepare('UPDATE users SET password_hash=?,password_salt=?,updated_at=? WHERE id=?').bind(await passwordHash(password,salt),salt,now(),c.user!.id),c.env.DB.prepare('DELETE FROM sessions WHERE user_id=? AND token_hash<>?').bind(c.user!.id,await hash(c.request.headers.get('authorization')!.replace(/^Bearer\\s+/i,'')))]);return json({ok:true})},{auth:true});
route('POST','/api/auth/password/reset',async c=>{const x=await body<{email:string}>(c.request),u=await c.env.DB.prepare('SELECT id,email FROM users WHERE email=? COLLATE NOCASE').bind(String(x.email||'').trim()).first<{id:string;email:string}>();if(u&&c.env.RESEND_API_KEY&&c.env.FROM_EMAIL&&c.env.APP_URL){const token=randomToken();await c.env.DB.prepare('INSERT INTO password_reset_tokens(id,user_id,token_hash,expires_at) VALUES(?,?,?,?)').bind(id(),u.id,await hash(token),new Date(Date.now()+3600000).toISOString()).run();const link=`${c.env.APP_URL.replace(/\/$/,'')}/reset-password?token=${encodeURIComponent(token)}`;const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{authorization:`Bearer ${c.env.RESEND_API_KEY}`,'content-type':'application/json'},body:JSON.stringify({from:c.env.FROM_EMAIL,to:[u.email],subject:'Reset your CloudGather password',html:`<p>Use the secure link below to reset your password. It expires in one hour.</p><p><a href="${link}">Reset password</a></p>`})});if(!response.ok)console.error(JSON.stringify({requestId:c.requestId,error:'reset email delivery failed',status:response.status}))}return json({ok:true,message:'If an account exists, reset instructions will be sent.'})});
route('POST','/api/auth/password/confirm',async c=>{const x=await body<{token:string;password:string}>(c.request),tokenHash=await hash(String(x.token||'')),row=await c.env.DB.prepare("SELECT id,user_id FROM password_reset_tokens WHERE token_hash=? AND used_at IS NULL AND expires_at>datetime('now')").bind(tokenHash).first<{id:string;user_id:string}>();if(!row)throw new HttpError(400,'This reset link is invalid or expired.');const salt=randomToken(),password=validatePassword(x.password);await c.env.DB.batch([c.env.DB.prepare('UPDATE users SET password_hash=?,password_salt=?,updated_at=? WHERE id=?').bind(await passwordHash(password,salt),salt,now(),row.user_id),c.env.DB.prepare('UPDATE password_reset_tokens SET used_at=? WHERE id=?').bind(now(),row.id),c.env.DB.prepare('DELETE FROM sessions WHERE user_id=?').bind(row.user_id)]);return json({ok:true})});
route('GET','/api/auth/oauth/:provider',async()=>{throw new HttpError(503,'This sign-in provider is not configured. Add its client ID and secret to the Worker environment.')});
route('GET','/api/files/:id/path',async c=>{const f=await c.env.DB.prepare('SELECT path FROM files WHERE id=? AND user_id=? AND is_folder=1').bind(c.params.id,c.user!.id).first<{path:string}>();if(!f)throw new HttpError(404,'Folder not found.');const parts=f.path.split('/').filter(Boolean);const folders=[];let path='';for(const part of parts){path+='/'+part;const row=await c.env.DB.prepare('SELECT * FROM files WHERE user_id=? AND path=?').bind(c.user!.id,path).first();if(row)folders.push(row)}return json({folders})},{auth:true});
route('GET','/api/files/:id/shares',async c=>json({shares:(await c.env.DB.prepare('SELECT * FROM file_shares WHERE file_id=? AND owner_id=? ORDER BY created_at DESC').bind(c.params.id,c.user!.id).all()).results}),{auth:true});
route('POST','/api/files/:id/shares',async c=>{const x=await body<{email:string;permission?:string;expires_at?:string|null}>(c.request),email=String(x.email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new HttpError(400,'Enter a valid email.');const owned=await c.env.DB.prepare('SELECT id FROM files WHERE id=? AND user_id=?').bind(c.params.id,c.user!.id).first();if(!owned)throw new HttpError(404,'File not found.');const sid=id();await c.env.DB.batch([c.env.DB.prepare('INSERT INTO file_shares(id,file_id,owner_id,shared_with_email,permission_level,expires_at) VALUES(?,?,?,?,?,?)').bind(sid,c.params.id,c.user!.id,email,x.permission==='edit'?'edit':'view',x.expires_at||null),c.env.DB.prepare('UPDATE files SET is_shared=1 WHERE id=?').bind(c.params.id)]);return json({share:await c.env.DB.prepare('SELECT * FROM file_shares WHERE id=?').bind(sid).first()},201)},{auth:true});
route('DELETE','/api/shares/:id',async c=>{const s=await c.env.DB.prepare('SELECT file_id FROM file_shares WHERE id=? AND owner_id=?').bind(c.params.id,c.user!.id).first<{file_id:string}>();if(!s)throw new HttpError(404,'Share not found.');await c.env.DB.prepare('DELETE FROM file_shares WHERE id=?').bind(c.params.id).run();const left=await c.env.DB.prepare('SELECT count(*) count FROM file_shares WHERE file_id=?').bind(s.file_id).first<{count:number}>();if(!left?.count)await c.env.DB.prepare('UPDATE files SET is_shared=0 WHERE id=?').bind(s.file_id).run();return new Response(null,{status:204})},{auth:true});
route('PATCH','/api/providers/order',async c=>{const x=await body<{ids:string[]}>(c.request);if(!Array.isArray(x.ids)||x.ids.length>100)throw new HttpError(400,'Invalid provider order.');await c.env.DB.batch(x.ids.map((pid,i)=>c.env.DB.prepare('UPDATE storage_providers SET priority=?,updated_at=? WHERE id=? AND user_id=?').bind(i+1,now(),pid,c.user!.id)));return json({ok:true})},{auth:true});
route('POST','/api/providers/connect',async()=>{throw new HttpError(503,'Provider credentials are not configured on this deployment.')},{auth:true});
route('GET','/api/providers/:provider/oauth',async()=>{throw new HttpError(503,'Provider OAuth is not configured on this deployment.')},{auth:true});
route('POST','/api/activity',async c=>{const x=await body<{action:string;resourceType?:string;resourceId?:string;details?:unknown}>(c.request);if(!x.action||x.action.length>100)throw new HttpError(400,'Invalid activity.');await audit(c,x.action,x.resourceType,x.resourceId,x.details);return json({ok:true},201)},{auth:true});
route('GET','/api/activity',async c=>{const limit=Math.min(Math.max(Number(c.url.searchParams.get('limit')||20),1),100);const rows=await c.env.DB.prepare('SELECT id,action,resource_type,resource_id,details,created_at FROM audit_logs WHERE user_id=? ORDER BY created_at DESC LIMIT ?').bind(c.user!.id,limit).all();return json({activity:rows.results.map((r:any)=>({...r,details:parse(r.details,{})}))})},{auth:true});
route('GET','/api/blog/:slug',async c=>{const post=await c.env.DB.prepare('SELECT * FROM blog_posts WHERE slug=? AND published=1').bind(c.params.slug).first();if(!post)throw new HttpError(404,'Post not found.');return json({post})});

export default {async fetch(request:Request,env:Env):Promise<Response>{const requestId=request.headers.get('cf-ray')||id(),headers=cors(request,env);if(request.method==='OPTIONS')return new Response(null,{status:204,headers});const url=new URL(request.url),ctx:Ctx={request,env,url,requestId,params:{}};try{const found=routes.find(r=>{if(r.method!==request.method)return false;const m=r.pattern.exec(url);if(!m)return false;ctx.params=m.pathname.groups as Record<string,string>;return true});if(!found)return withHeaders(error('Route not found.',404,requestId),headers,requestId);if(found.auth||found.admin)await session(ctx);if(found.admin&&ctx.user?.role!=='admin')throw new HttpError(403,'Administrator access required.');if(ctx.apiPermissions){const needed=request.method==='GET'?'read':url.pathname.includes('/shares')?'share':'write';if(!ctx.apiPermissions.includes(needed))throw new HttpError(403,`API key lacks the ${needed} permission.`)}return withHeaders(await found.handler(ctx),headers,requestId)}catch(e){console.error(JSON.stringify({requestId,path:url.pathname,error:e instanceof Error?e.message:String(e)}));const status=e instanceof HttpError?e.status:500;return withHeaders(error(status===500?'An unexpected error occurred.':(e as Error).message,status,requestId),headers,requestId)}}};
function withHeaders(response:Response,headers:Headers,requestId:string){const out=new Response(response.body,response);headers.forEach((v,k)=>out.headers.set(k,v));out.headers.set('x-request-id',requestId);out.headers.set('x-content-type-options','nosniff');out.headers.set('cache-control',response.status===204?'no-store':out.headers.get('cache-control')||'no-store');return out}
