// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqbtzqgvbhooyzkwfhzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xYnR6cWd2Ymhvb3l6a3dmaHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NzEzMjEsImV4cCI6MjA1OTI0NzMyMX0.YXBEf8T-eSTuUv78tCpyhnRR1ge_CE5177zA_3tsXtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);